export const languagesMapRecorder = {
  "South Africa": "af-ZA",
  Algeria: "ar-DZ",
  Bahrain: "ar-BH",
  Egypt: "ar-EG",
  Israel: "ar-IL",
  Iraq: "ar-IQ",
  Jordan: "ar-JO",
  Kuwait: "ar-KW",
  Lebanon: "ar-LB",
  Morocco: "ar-MA",
  Oman: "ar-OM",
  "Palestinian Territory": "ar-PS",
  Qatar: "ar-QA",
  "Saudi Arabia": "ar-SA",
  Tunisia: "ar-TN",
  UAE: "ar-AE",
  Spain: "eu-ES",
  Bulgaria: "bg-BG",
  "China (Simp.)": "cmn-Hans-CN",
  "Hong Kong SAR (Trad.)": "cmn-Hans-HK",
  "Taiwan (Trad.)": "cmn-Hant-TW",
  "Hong Kong": "yue-Hant-HK",
  Croatia: "hr_HR",
  "Czech Republic": "cs-CZ",
  Denmark: "da-DK",
  Australia: "en-AU",
  Canada: "en-CA",
  India: "en-IN",
  Ireland: "en-IE",
  "New Zealand": "en-NZ",
  "United Kingdom": "en-GB",
  "United States": "en-US",
  Iran: "fa-IR",
  France: "fr-FR",
  Philippines: "fil-PH",
  Germany: "de-DE",
  Greece: "el-GR",
  Finland: "fi-FI",
  Hungary: "hu-HU",
  Indonesia: "id-ID",
  Iceland: "is-IS",
  Italy: "it-IT",
  Switzerland: "it-CH",
  Japan: "ja-JP",
  Korea: "ko-KR",
  Lithuania: "lt-LT",
  Malaysia: "ms-MY",
  Netherlands: "nl-NL",
  Norway: "nb-NO",
  Poland: "pl-PL",
  Brazil: "pt-BR",
  Portugal: "pt-PT",
  Romania: "ro-RO",
  Russia: "ru-RU",
  Serbia: "sr-RS",
  Slovakia: "sk-SK",
  Slovenia: "sl-SI",
  Argentina: "es-AR",
  Bolivia: "es-BO",
  Chile: "es-CL",
  Colombia: "es-CO",
  "Costa Rica": "es-CR",
  "Dominican Republic": "es-DO",
  Ecuador: "es-EC",
  "El Salvador": "es-SV",
  Guatemala: "es-GT",
  Honduras: "es-HN",
  México: "es-MX",
  Nicaragua: "es-NI",
  Panamá: "es-PA",
  Paraguay: "es-PY",
  Perú: "es-PE",
  "Puerto Rico": "es-PR",
  Uruguay: "es-UY",
  Venezuela: "es-VE",
  Sweden: "sv-SE",
  Thailand: "th-TH",
  Turkey: "tr-TR",
  Ukraine: "uk-UA",
  "Viet Nam": "vi-VN",
} as any;
